version: "3"
services:
  react-app:
    build: ./frontend
    container_name: react-docker  
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    #   - ./app/node_modules

  api-server:
    build: ./backend
    container_name: node-docker  
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      DATABASE_URI_LOCAL: mongodb://mongo_db:27017/db
    # volumes:
    #   - ./backend:/app
    #   - ./app/node_modules

    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    restart: always
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - mern-app
    volumes:
      - mongo_db:/data/db

  # networks:
  #   mern-app:
  #     driver: bridge

volumes:
  mongo_db: {}