version: "3"
services:
  react-app:
    build: ./frontend
    container_name: react-docker  
    ports:
      - "3000:3000"
    # volumes:
    #   - ./frontend:/app
    #   - ./app/node_modules

  api-server:
    build: ./backend
    container_name: node-docker  
    ports:
      - "8000:8000"
    # volumes:
    #   - ./backend:/app
    #   - ./app/node_modules

  #   depends_on:
  #     - mongo

  # mongo:
  #   image: mongo:3.6.19-xenial
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - mern-app
  #   volumes:
  #     - mongo-data:/data/db

  # networks:
  #   mern-app:
  #     driver: bridge

  # volumes:
  #   mongo-data:
  #     driver: local